### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by l0go** [FurretDev/hxdiscord#10]
The bot never starts up and the application stalls.

**Comment by l0go** [comment]
Tested on neko + hl target

**Comment by furretpaws** [comment]
Late reply, I know, but this is due to the bots intents not being enabled
Go to your bots settings, and enable ALL special intents. You can also not use any intents (modify the [Intents.ALL] argument), the bot will run but it won't be able to read any messages or almost anything, I think interactions are the only thing allowed when no intents are specified.

Settings to enable: https://prnt.sc/Xb6KToqeEOfy
